name: Upload MongoDB Data

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: check out code
        uses: actions/checkout@v2

      - name: set up python 
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Upload imported data
        uses: actions/upload-artifact@v4
        with:
          name: mongodb-imported-data
          path: raw_data.csv    

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt    


      - name: Test with pytest
        run: pytest