name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: check out code
        uses: actions/checkout@v2

      - name: set up python 
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  

      - name: read DB_NAME
        run: echo "My DB_NAME is ${{secrets.DB_NAME}}" >> .env   

      - name: read COLLECTION_NAME
        run: echo "My COLLECTION_NAME is ${{secrets.COLLECTION_NAME}}" >> .env  


      - name: read CONNECTION_URL
        run: echo "My CONNECTION_URL is ${{secrets.CONNECTION_URL}}" >> .env         


      - name: Test with pytest
        run: pytest